### ISSUE TITLE
miner-manager miner version installed/avaible

### ISSUE THREAD

**Issue by tutorialevideo** [cynixx3/third-party-miner-installer-for-ethos#38]
Hi,
on a simple miner-manager command can you show what version of miners do you install ?

 miner-manager
Wrong number of arguments, must be 2 arguments miner and action, please refer to https://github.com/cynixx3/third-party-miner-installer-for-ethos
Usage /usr/bin/miner-manager [ Miner ] ( install | update | revert )

Miners Available:
bminer **VERSION avaible for install**
cast-xmr
cryptodredge
energiminer
grin-miner
gringoldminer
grinpro
lolminer
nbminer
nodecore-pow-amd-cuda-miner
nodecore-pow-cuda-miner
phoenixminer
soliditysha3miner
t-rex
teamredminer
ubqminer
wildrig-multi
xmr-stak
xmrig-amd
zilminer

**Comment by cynixx3** [comment]
Good idea, I could pull the current version for each, but that would add a lot of API calls and significantly reduce the number of installs allowed on a network. 

I will ponder a solution that would not harm large installations.

**Comment by cynixx3** [comment]
I have decided to add the miner version or where we get the miner from to the main readme rather than to the help menu, this helps users and developers identify if action is needed for the miner-manager when a miner updates. When the readme lists "Latest" then users can get their information directly from the miner's developer and no action is needed for the miner-manager to apply it. Otherwise we would update the hardlink in miner.settings or compile and host a new release. 

I am not including it in the help menu because after with playing with the code to pull the miner version it became apparent that this should be a separate update detection script that would either let you know about the miners update or automatically update it. 

Thank you for the idea.
